config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
   root "welcome#index"
   resources :students
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/student.rb
class Student < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  def index
    @students = Student.all
  end

  def new
    @student = Student.new
  end

  def create
    @student = Student.new(student_params)
    if @student.save
      redirect_to students_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    # Add any logic or instance variables needed for the show action
  end

  def edit
    # Add any logic or instance variables needed for the edit action
  end

  def update
    if @student.update(student_params)
      redirect_to students_path
    else
      render :edit
    end
  end

  def destroy
    @student.destroy
    redirect_to students_path
  end

  private

  def student_params
    params.require(:student).permit(:first_name, :last_name, :email)
  end

  def set_student
    @student = Student.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StudentMgmt</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

  <%= yield %>

  </body>
</html>

app/views/students/edit.html.erb
<h1>Edit Student</h1>
<%= form_with model: @student do |form| %>

  <% if @student.errors.any? %>
    <% @student.errors.full_messages.each do |message| %>
      <p><%= message %></p>
    <% end %>
  <% end %>
  <div>
    <%= form.label :first_name %><br>
    <%= form.text_field :first_name %>
  </div>

  <div>
    <%= form.label :last_name %><br>
    <%= form.text_field :first_name %>
  </div>

  <div>
    <%= form.label :email %><br>
    <%= form.text_field :email %>

  </div>
  <div>
    <%= form.submit :UpdateStudent %><br>

  </div>
<% end %>

app/views/students/index.html.erb
<h1>Listing Student Names</h1>
<%= link_to 'New Students', new_student_path %>
<table>
  <thead>
  <tr>
    <th>First Name</th>
    <th>Last Name</th>
    <th>Email</th>
    <th colspan="3">Action</th>
  </tr>
  </thead>
  <tbody>
  <% @students.each do |student| %>
    <tr>
      <td><%= student.first_name %></td>
      <td><%= student.last_name %></td>
      <td><%= student.email %></td>
      <td><%= link_to 'View', student %></td>
      <td><%= link_to 'Edit ', edit_student_path(student) %></td>
      <td> <%= link_to 'Delete', '#', class: 'delete-link',
                       data: { confirm: 'Are you sure you want to delete?' },
                       "data-url": student_path(student) %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/students/new.html.erb
<h1>New Student</h1>
<%= form_with model: @student do |form| %>
  <% if @student.errors.any? %>
    <% @student.errors.full_messages.each do |message| %>
      <p><%= message %></p>
    <% end %>
  <% end %>
  <div>
    <%= form.label :first_name %><br>
    <%= form.text_field :first_name %>
  </div>

  <div>
    <%= form.label :last_name %><br>
    <%= form.text_field :last_name %>
  </div>

  <div>
    <%= form.label :email %><br>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.submit %><br>
  </div>
<% end %>

app/views/students/show.html.erb
<h1>Students Details </h1>
<p><strong>First Name: </strong><%= @student.first_name %></p>
<p><strong>Last Name: </strong><%= @student.last_name %></p>
<p><strong>Email: </strong><%= @student.email %></p>

<%= link_to 'Back', students_path %>| <td><%= link_to 'Edit ', edit_student_path(@student) %></td>

app/views/welcome/index.html.erb
<h1>Welcome Index Page</h1>